### ISSUE TITLE
Namespace for choo events

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/choo#547]
From the discussion in [Nanocomponent#45](https://github.com/choojs/nanocomponent/issues/45), what do you say about a namespace for events. I can see two benefits, 1) It would prevent dumb errors like mine in the nanocomponent issue thread, and 2) it would be consistent with, for instance, choo-log, and any other namespaced choo plugin.

**Comment by yoshuawuyts** [comment]
The reasoning for not namespacing choo's internal events was because they
map directly to the global browser events (mostly, best attempt in most
cases).

The intent was that by keeping these events as they are, people would learn
about the browser, as they learn Choo.

The drawback, as shown here, is that when adding new events they might
conflict with what people are using. Especially with something as generic
as 'navigate'. The upside, however, is that we've now covered most of the
events, and are unlikely to add more.

When considering adding namespaces to Choo's built-in events, it must also
be considered that Choo recently has gotten a reputation of making lots of
backwards incompatible changes. While this has been true in the past, I
think it'd be nice if we could distance ourselves from that and remain
API-stable between major versions.

**Comment by YerkoPalma** [comment]
Fair enough :smile:
