### ISSUE TITLE
Add choo/md renderer?

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/choo#555]
I've just made [a module](https://github.com/YerkoPalma/marli) that works like [bel](https://github.com/shama/bel) but rendering markdown with tagged templates. I thought it would be useful to have something like this in choo, so views could be written like this

```js
var md = require('choo/md')
var choo = require('choo')

var app = choo()
app.route('/', mainView)
app.mount('main')

function mainView (state, emit) {
  return md`
    ## Hello ${state.name}
  `
}
```

What do you thinik? Would it add some value to choo?

**Comment by yoshuawuyts** [comment]
Ohhh, I've been wanting something like this! I think it should be a
separate package tho; it should be easy enough to add I reckon (:

If you added a constructor then it could also accept highlighting like
marked, using https://substack.neocities.org/highlight-syntax/index.html.

And because it's a literal, it means you could also create a transform in
the same source so it comes at no overhead ever! Would be so sick!

Anyway, I'm really excited by this, and the options it provides - don't
think we should add it to choo core (at least not right now, opinions
change), just because we're so narrowly scoped, but itd be amazing to
expand this further!

**Comment by YerkoPalma** [comment]
[marli](https://github.com/YerkoPalma/marli) already accept lots of options, it uses [markdown-it ](https://github.com/markdown-it/markdown-it) under the hood which accepts, among others, a [highlight option](https://github.com/markdown-it/markdown-it#syntax-highlighting). It should work with `highlight-syntax` out of the box like

```js
var Marli = require('marli')
var highlight = require('highlight-syntax/all')

var md = Marli ({
  highlight: function (str, lang) {
    if (lang) {
      try {
        return highlight(src, { lang: lang })
      } catch (__) {}
    }

    return ''
  }
})
```

**Comment by YerkoPalma** [comment]
@yoshuawuyts I've just added a highlighted example

- https://github.com/YerkoPalma/marli

**Comment by yoshuawuyts** [comment]
Yayay! :D

**Comment by bcomnes** [comment]
Bel just added https://github.com/shama/bel#unescaping as well. May want to expose that too.
